networks:
  stage:
    driver: overlay
    ipam:
      config:
        - subnet: 172.28.0.0/16

secrets:
  emqx-rest:
    external: true

services:
  emqx-node:
    image: ghcr.io/blabtm/emqx:latest
    environment:
      EMQX_API_KEY__BOOTSTRAP_FILE: /etc/secret.cfg
      EMQX_CLUSTER__DISCOVERY_STRATEGY: dns
      EMQX_CLUSTER__DNS__NAME: emqx-node
      EMQX_CLUSTER__DNS__RECORD_TYPE: a
    secrets:
      - source: emqx-rest
        target: /etc/secret.cfg
    networks:
      - stage
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr

  emqx:
    image: ghcr.io/blabtm/emqx-proxy:latest
    ports:
      - 1883:1883
      - 18083:18083
      - 20041:20041
    environment:
      NODE_NAME: emqx-node
      NODE_PORT_MQTT: 1883
      NODE_PORT_DASH: 18083
      NODE_PORT_VCAS: 20041
      NODE_PORT_ADAP: 9100
      PORT_MQTT: 1883
      PORT_DASH: 18083
      PORT_VCAS: 20041
      PORT_ADAP: 9100
    networks:
      - stage
    deploy:
      mode: replicated
      replicas: 1

  emqx-gate-node:
    image: ghcr.io/blabtm/emqx-gate:latest
    environment:
      LOG: debug
      PORT: 9001
      EMQX_ADAP_HOST: emqx
      EMQX_ADAP_PORT: 9100
    networks:
      - stage
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr

  emqx-gate:
    image: ghcr.io/blabtm/emqx-gate-proxy:latest
    environment:
      NODE_NAME: emqx-gate-node
      NODE_PORT: 9001
      PORT: 9001
      NETWORK: 172.28.0.0/16
      EMQX_HOST: emqx
      EMQX_PORT_DASH: 18083
      EMQX_PORT_ADAP: 9100
      EMQX_USER: user
      EMQX_PASS: pass
    networks:
      - stage
    deploy:
      mode: replicated
      replicas: 1
  # emqx-psql-node:
  #   image: ghcr.io/blabtm/emqx-psql:latest
  #   environment:
  #     PORT: 9004
  #   networks:
  #     - stage
  #   deploy:
  #     mode: replicated
  #     replicas: 2
  #     endpoint_mode: dnsrr

  # emqx-psql:
  #   image: ghcr.io/blabtm/emqx-psql-proxy:latest
  #   environment:
  #     NODE_NAME: emqx-psql-node
  #     NODE_PORT: 9004
  #     PORT: 9002
  #     NETWORK: 172.28.0.0/16
  #     EMQX_HOST: emqx
  #     EMQX_PORT_DASH: 18083
  #     EMQX_USER: user
  #     EMQX_PASS: pass
  #   networks:
  #     - stage
  #   deploy:
  #     mode: replicated
  #     replicas: 1

  # grafana:
  #   image: ghcr.io/blabtm/grafana:latest
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - stage
  #   deploy:
  #     mode: replicated
  #     replicas: 1
